apiVersion: v1
kind: Service
metadata:
  name: sevasetu-service
spec:
  selector:
    app: sevasetu
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000
  type: LoadBalancer
---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: sevasetu-hpa
spec:
  scaleTargetRef:
    apiVersions: apps/v1
    kind: Deployment
    name: sevasetu-deployment
  minReplicas: 2
  maxReplicas: 10
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 70
